services:
  postgres:
    image: postgres:15
    container_name: kanban_management_system_postgres_db
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    volumes:
      - ./db-changes:/flyway/sql
    env_file:
      - .env
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      -connectRetries=10
      -baselineOnMigrate=true
       migrate
volumes:
  pgdata:
